### ISSUE TITLE
Please add Chargemaker 

### ISSUE THREAD

**Issue by wtremmel** [functionpointer/home-assistant-chargecloud-integration#6]
Hello,

the following URL works from the commandline:

https://api.chargecloud.de/rest:contract/830de8931b1d8dff36808d2173a57735/getEmobilityLocationsDataDetails?offset=0&limit=100&evseId=DE*CM1*E1100192*AC001

but the integration shows an empty response....  is the 830... an Operator ID and missing?

best regards
Wolfgang

**Comment by wtremmel** [comment]
Yes it is - added it in my local copy and works like a charm....

**Comment by functionpointer** [comment]
Released as [v1.2.1](https://github.com/functionpointer/home-assistant-chargecloud-integration/releases/tag/v1.2.1)
