### ISSUE TITLE
Allego stations stopped working?

### ISSUE THREAD

**Issue by HaWaKv78** [functionpointer/home-assistant-chargecloud-integration#7]
Hi, I had 2 Allego stations (BEALLEGO0014661 & BEALLEGO0014662) added in my home assistant and they stopped working all of the sudden, the status didn't change anymore. I removed them and tried to add but I get an error response "Empty reponse from chargecloud.de. Either invalid EVSE-ID or no data for it."
I tried some random evse-ids from France (FRALLEGO9000951), Germany (DEALLEGO0025251) and the Netherlands (NLALLEGO0015491), some can be added some give the same error. Any idea if this can be an issue in the integration or should I look somewhere else?

**Comment by zombiemann1** [comment]
Hi, I have the same issue with my monitored ALLEGO charging stations.
This was working before : BE*ALL*EGO0006651, BE*ALL*EGO0006652, BE*ALL*EGO0006641, BE*ALL*EGO0006642, ...
But they are not working anymore.
When I look up the charging station on the map of https://ladenetz.de/privatpersonen/, they also doesn't appear anymore.
Please investigate why these charging points are not monitored anymore.

**Comment by zombiemann1** [comment]
Looks like Allego EV charging station did popup again.
There are monitored again by this plugin.
So that's great news!
